(cl:defpackage inference_pkg-srv
  (:use )
  (:export
   "INFERENCESTATESRV"
   "<INFERENCESTATESRV-REQUEST>"
   "INFERENCESTATESRV-REQUEST"
   "<INFERENCESTATESRV-RESPONSE>"
   "INFERENCESTATESRV-RESPONSE"
   "LOADMODELSRV"
   "<LOADMODELSRV-REQUEST>"
   "LOADMODELSRV-REQUEST"
   "<LOADMODELSRV-RESPONSE>"
   "LOADMODELSRV-RESPONSE"
   "MODELOPTIMIZE"
   "<MODELOPTIMIZE-REQUEST>"
   "MODELOPTIMIZE-REQUEST"
   "<MODELOPTIMIZE-RESPONSE>"
   "MODELOPTIMIZE-RESPONSE"
  ))

